### ISSUE TITLE
How can I sync?

### ISSUE THREAD

**Issue by ahmedmohiduet** [fadeit/prerender-postgre-cache#1]
I am using prerender node server for javascript SEO on my webpages. I am trying to use 'prerender-postgre-cache' with it. I am unsure of which would be the best approach for periodically updating/syncing my cache with my current web pages.

**Comment by ozooner** [comment]
Hi Ahmed,

We have built a small python crawler that reads sitemap.xml and then makes POST requests (with ?_escaped_fragment_=) to the pages in sitemap to update cache (as a cronjob). Since our database is rather large (50k+ pages), we added triggers to tables to keep track of update date on each model so we can skip caching pages that haven't been updated.

**Comment by ahmedmohiduet** [comment]
Thanks for the info! :) Looks like I'll have to follow the same way! :)
